version: 2

# Docker environment.
defaults: &defaults
  working_directory: /go/src/github.com/kubeedge/kubeedge
  docker:
  - image: circleci/golang:1.11.1

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - run: make

  verify:
    <<: *defaults
    steps:
    - checkout
    - run:
        command: make verify

  test:
    <<: *defaults
    steps:
    - checkout
    - run:
        command: make test

  integration:
    <<: *defaults
    steps:
    - checkout
    - run:
        command: make integration_test

workflows:
  version: 2
  workflow:
    jobs:
    - verify
    - build
    - test
    - integration
