apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudcore
  {{- with .Values.cloudCore.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  cloudcore.yaml: |
    apiVersion: cloudcore.config.kubeedge.io/v1alpha2
    kind: CloudCore
    featureGates:
      requireAuthorization: {{ .Values.cloudCore.featureGates.requireAuthorization }}
    kubeAPIConfig:
      kubeConfig: ""
      master: ""
    modules:
      cloudHub:
        advertiseAddress:
        {{- range .Values.cloudCore.modules.cloudHub.advertiseAddress }}
        - {{  .  }}
        {{- end}}
        dnsNames:
        {{- range .Values.cloudCore.modules.cloudHub.dnsNames }}
        - {{  .  }}
        {{- end}}
        nodeLimit: {{ .Values.cloudCore.modules.cloudHub.nodeLimit }}
        tlsCAFile: /etc/kubeedge/ca/rootCA.crt
        tlsCertFile: /etc/kubeedge/certs/edge.crt
        tlsPrivateKeyFile: /etc/kubeedge/certs/edge.key
        unixsocket:
          address: unix:///var/lib/kubeedge/kubeedge.sock
          enable: true
        websocket:
          address: 0.0.0.0
          enable: {{ .Values.cloudCore.modules.cloudHub.websocket.enable }}
          port: {{ .Values.cloudCore.modules.cloudHub.websocket.port }}
        quic:
          address: 0.0.0.0
          enable: {{ .Values.cloudCore.modules.cloudHub.quic.enable }}
          maxIncomingStreams: {{ .Values.cloudCore.modules.cloudHub.quic.maxIncomingStreams }}
          port: {{ .Values.cloudCore.modules.cloudHub.quic.port }}
        https:
          address: 0.0.0.0
          enable: {{ .Values.cloudCore.modules.cloudHub.https.enable }}
          port: 10002
      cloudStream:
        enable: {{ .Values.cloudCore.modules.cloudStream.enable }}
        streamPort: 10003
        tunnelPort: 10004
      dynamicController:
        enable: {{ .Values.cloudCore.modules.dynamicController.enable }}
      router:
        enable: {{ .Values.cloudCore.modules.router.enable }}
      iptablesManager:
        enable: {{ .Values.iptablesManager.enable }}
        mode: {{ .Values.iptablesManager.mode }}
      taskManager:
        enable: {{ .Values.cloudCore.modules.taskManager.enable }}
