apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudcore-common
  labels:
    rbac/aggregate-to-cloudcore: "true"
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/status", "serviceaccounts/token", "configmaps", "pods", "pods/status", "secrets", "endpoints", "services", "persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes", "nodes/status", "pods/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: ["devices.kubeedge.io"]
    resources: ["devices", "devicemodels", "devices/status", "devicemodels/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["reliablesyncs.kubeedge.io"]
    resources: ["objectsyncs", "clusterobjectsyncs", "objectsyncs/status", "clusterobjectsyncs/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rules.kubeedge.io"]
    resources: ["rules", "ruleendpoints", "rules/status", "ruleendpoints/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.istio.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["operations.kubeedge.io"]
    resources: ["nodeupgradejobs", "nodeupgradejobs/status", "imageprepulljobs", "imageprepulljobs/status", "configupdatejobs", "configupdatejobs/status"]
    verbs: ["get", "list", "watch", "update", "patch"]

